Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2023-08, with the labels that each got.

#3 feat(gha): add check pr size and continuous deploy workflows
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
Labels: skip-release

#2 feat(.devops) added devops pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
Labels: size/large, ignore-for-release

#5 chore(build): integrate ecommerce commons library
  .devops/code-review-pipelines.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  pagopa-ecommerce-commons-maven-install.sh
Labels: skip-release, size/large

#6 feat(oracle): add configuration for reactive oracle connection and mongo db
  .env.example
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/configurations/OracleConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/PmService.kt
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: skip-release, size/large

#10 fix: add user informations
  api-spec/openapi.yaml
Labels: skip-release, size/small

#11 fix(openapi): update openapi with latest modifications
  api-spec/openapi.yaml
  settings.gradle.kts
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/PmService.kt
Labels: skip-release, size/small

#12 Exception handling
  build.gradle.kts
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/EcommerceController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptions/ApiError.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptions/NoResultFoundException.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptions/RestApiException.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/PmService.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/configurations/OracleConfigurationTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/EcommerceControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandlerTest.kt
Labels: skip-release, size/large

#13 feat: add search by user fiscal code
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PmQueries.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/PmServiceTest.kt
  src/test/resources/h2scriptFile.sql
Labels: skip-release, size/small

#15 fix(openapi): make payment detail info a list
  api-spec/openapi.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ResponseBuilder.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProviderTest.kt
Labels: skip-release, size/small

#19 fix(500) removed error details
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/EcommerceControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandlerTest.kt
Labels: patch, chart-patch, size/small

#20 Fix pagination
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskService.kt
Labels: patch, chart-patch, size/small
