Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2024-12, with the labels that each got.

#168 [PPABV-74] Edit PM DB docker service
  docker-compose.yml
  docker/oracleDB/liquibase/Dockerfile.ext
  docker/oracleDB/liquibase/ext/changelogs/payment-manager/data-insert-changelog.xml
  docker/oracleDB/liquibase/ext/changelogs/payment-manager/scripts/data-insert/V37__PM__INSERT_TRANSACTION.sql
  docker/oracleDB/liquibase/ext/changelogs/payment-manager/scripts/schema-creation/V0__CREATE_USER.sql
  docker/oracleDB/liquibase/ext/rollback_image.sh
  docker/oracleDB/liquibase/ext/run_image.sh
Labels: skip-release, size/large, ignore-for-release

#169 [PPABV-72] feat: added new case on dataprovider
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/oracle/PMTransactionDataProvider.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/v1/PMTransactionDataProviderTest.kt
Labels: size/small, minor, chart-minor

#167 [PPABV-73] feat: add pm search transaction by date to test API collection
  api-tests/v1/eCommerce-helpdesk.api.tests.local.json
  api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
Labels: size/large, minor, chart-minor

#172 [PPABV-79] fix: add alias for ambiguous columns
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/oracle/PmQueries.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/v1/PmQueriesTest.kt
Labels: size/small, minor, chart-minor
