Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2024-11, with the labels that each got.

#141 [PPABV-30] Add data provider pm mongodb
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/repositories/history/PmTransactionsRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/PmTransactionHistoryDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/documents/PmTransactionHistory.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/documents/PmTransactionHistoryStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/ResponseBuilderV1.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtilsV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/PmTransactionHistoryDataProviderTestV2.kt
Labels: size/large, minor, chart-minor

#142 [PPABV-32] feat: add search for pm transactions in ecommerce history
  docker/mongoDB/mongo-init.js
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/PmController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/PmProviderType.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskControllerTestEcommerceHistory.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskControllerTestLegacy.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskServiceTest.kt
Labels: size/small, minor, chart-minor

#144 [PPABV-40] feat: enable search pm in ecommerce history
  helm/values-dev.yaml
Labels: size/small, minor, chart-minor

#143 [PPABV-33] feat: add test api to local/dev collections for 200 response
  api-tests/v2/eCommerce-helpdesk.api.tests.local.json
  docker/mongoDB/mongo-init.js
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/documents/PmTransactionHistory.kt
Labels: size/small, minor, chart-minor

#146 [PPABV-50] feat: add paymentEndToEndId in openapi.yaml
  api-spec/v1/openapi.yaml
Labels: size/small, minor, chart-minor

#145 [PPABV-42] fix: add missing search transaction test APIs to dev collection
  api-tests/env/helpDesk_dev.env.json
  api-tests/env/helpDesk_local.env.json
  api-tests/env/helpDesk_uat.env.json
  api-tests/env/helpDesk_uat_blue.env.json
  api-tests/v2/eCommerce-helpdesk.api.tests.dev.json
  api-tests/v2/eCommerce-helpdesk.api.tests.local.json
  api-tests/v2/eCommerce-helpdesk.api.tests.uat.json
  docker/pagopa-personal-data-vault-tokenizer/src/db.json
  docker/pagopa-personal-data-vault-tokenizer/src/middleware.js
Labels: size/large, minor, chart-minor

#149 [PPABV-49] feat: add paymentEndToEndId into mapToTransactionInfoDetailsDto
  build.gradle.kts
  gradle.lockfile
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/mongo/DeadLetterDataProvider.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
Labels: size/small, minor, chart-minor

#148 [PPABV-51] feat: added USER_EMAIL_HISTORY env variable
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
  api-tests/env/helpDesk_dev.env.json
Labels: size/small, minor, chart-minor

#150 [PPABV-58] feat: add mock NPG on docker-compose
  docker-compose.yml
  docker/npg-mock/Dockerfile.npg-mock
  docker/npg-mock/db.json
  docker/npg-mock/middleware.js
  docker/npg-mock/routes.json
Labels: skip-release, ignore-for-release

#151 fix: deployment strategy
  helm/values-prod.yaml
Labels: patch, chart-patch, size/small

#153 [PPABV-43] feat: added new endpoint
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/HelpdeskController.kt
Labels: skip-release, ignore-for-release, size/small

#152 [PPABV-55] feat: add NPG client/config to v1 HelpdeskService
  .env.example
  README.md
  docker-compose.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/configurations/PaymentGatewayConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/PagopaEcommerceHelpdeskServiceApplicationKtTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/configurations/TracingConfigTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskServiceTest.kt
  src/test/resources/application.properties
Labels: size/small, minor, chart-minor

#161 [PPABV-57] Edit api path searchNpgOperations
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/HelpdeskController.kt
Labels: patch, chart-patch, size/small

#154 fix: api test config for ecommerce-history
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
  api-tests/env/helpDesk_dev.env.json
Labels: skip-release, ignore-for-release, size/small

#156 [PPABV-45] feat: add logic for searching NPG operations to HelpdeskServiceV1
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/mongo/EcommerceTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptions/NpgExceptions.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptions/UnsupportedTransactionVersionException.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskService.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v1/EcommerceForTransactionV1DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/EcommerceServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/TransactionInfoUtils.kt
Labels: minor, chart-minor

#158 [PPABV-44] feat: implemented controller for searchNpgOperations
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceController.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceControllerTest.kt
Labels: size/small, minor, chart-minor

#163 [PPABV-46] feat: modified the test api for the new endpoint
  api-tests/env/helpDesk_dev.env.json
  api-tests/env/helpDesk_local.env.json
  api-tests/env/helpDesk_uat.env.json
  api-tests/v1/eCommerce-helpdesk.api.tests.dev.json
  api-tests/v1/eCommerce-helpdesk.api.tests.local.json
  api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
Labels: size/large, patch, chart-patch

#165 [PPABV-71] fix: changed the value of the uat environment variable
  api-tests/env/helpDesk_uat.env.json
Labels: size/small, minor, chart-minor

#164 [PPABV-70] feat: add date time range filter on pm transaction search API
  api-spec/v1/openapi.yaml
Labels: skip-release, ignore-for-release, size/small

#166 [PPABV-75] feat: add date filter queries for pm transactions search
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/oracle/PmQueries.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/v1/PmQueriesTest.kt
Labels: skip-release, ignore-for-release, size/small
