Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2024-01, with the labels that each got.

#23 feat(helpdesk) CHK-1865 implemented business logic for retrieve user wallet by fiscal code or email
  api-spec/openapi.yaml
  api-tests/eCommerce-helpdesk.api.tests.uat.json
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/PaymentMethodDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMPaymentMethodsDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PmQueries.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/PmService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ResponseBuilderV1.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMPaymentMethodsDataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/PmServiceTest.kt
  src/test/resources/h2scriptFile.sql
Labels: size/large, minor, chart-minor

#59 CHK-1865 fix: convert into response after statement
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMPaymentMethodsDataProvider.kt
Labels: patch, chart-patch, size/small

#60 CHK-2865 fix: Default handling for inconsistent payment method
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ResponseBuilderV1.kt
Labels: patch, chart-patch, size/small

#56 feat(api tests): add api tests for PGS status + dead letter tests fix
  api-tests/eCommerce-helpdesk.api.tests.dev.json
  api-tests/eCommerce-helpdesk.api.tests.uat.json
  api-tests/env/helpDesk_dev.env.json
  api-tests/env/helpDesk_uat.env.json
  api-tests/env/helpDesk_uat_blue.env.json
Labels: skip-release

#66 feat: add search by email for eCommerce
  build.gradle.kts
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/TransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/TransactionsViewRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/PmService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialMailUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/SearchParamDecoder.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV1DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV2DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/PmServiceTest.kt
Labels: minor, chart-minor

#65 feat: add redirect transaction handling
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ResponseBuilderV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV2DataProviderTest.kt
Labels: size/small, minor, chart-minor

#68 fix: [CHK-2323] use same decoder search param to enable pdv cache
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskService.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskServiceTest.kt
Labels: patch, chart-patch, size/small

#71 [CHK-2397] feat: modified common version end handled new CLOSURE_REQUESTED v2 event
  build.gradle.kts
  gradle.lockfile
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV1DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV2DataProviderTest.kt
Labels: size/small, minor, chart-minor
