Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2025-05, with the labels that each got.

#209 [CHK-4115] chore(dep): update pagopa-commons library version
  build.gradle.kts
  gradle.lockfile
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/mongo/EcommerceTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/EcommerceTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialFiscalCodeUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v1/ConfidentialMailUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v1/ResponseBuilderV1.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v1/ResponseBuilderV2.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v1/SearchParamDecoder.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/ConfidentialMailUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/ResponseBuilderV1.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/ResponseBuilderV2.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/SearchParamDecoderV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v1/EcommerceForTransactionV1DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v1/EcommerceForTransactionV2DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/EcommerceForTransactionV1DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/EcommerceForTransactionV2DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/EcommerceServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialFiscalCodeUtilsTests.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialMailUtilsTestsV1.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialMailUtilsTestsV2.kt
Labels: size/small, minor, chart-minor

#208 chore: enable search by user fiscal code in eCommerce DB
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/EcommerceTransactionDataProvider.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/EcommerceForTransactionV1DataProviderTest.kt
Labels: patch, chart-patch, size/small

#198 [CHK-4049] Update integration tests
  api-tests/v2/eCommerce-helpdesk.api.tests.dev.json
Labels: skip-release, size/small

#206 fix: [PIDM-495] updated helm version
  helm/Chart.lock
  helm/Chart.yaml
Labels: ignore-for-release, size/small, chart-minor
