Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2025-07, with the labels that each got.

#217 feat(api-key): [CHK-4215] update openapi api key and add api key vali…
  .env.example
  README.md
  api-spec/v1/openapi.yaml
  api-spec/v2/openapi.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ApiKeyFilter.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/PmControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/EcommerceControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskControllerTestEcommerceHistory.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskControllerTestLegacy.kt
  src/test/resources/application.properties
Labels: size/small, minor, chart-minor

#222 feat(api-key): [CHK-4302] updated integration tests
  .env.example
  api-tests/env/helpDesk_local.env.json
  api-tests/v1/eCommerce-helpdesk.api.tests.local.json
  api-tests/v2/eCommerce-helpdesk.api.tests.local.json
Labels: size/large, minor, chart-minor

#223 chore(api test): remove v1 tests that perform queries against old PM DB
  api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
Labels: skip-release

#218 feat: [CHK-4223] upgrade java version to 21
  .devops/code-review-pipelines.yml
  .github/workflows/semver_release.yaml
  Dockerfile
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pagopa-ecommerce-commons-maven-install.sh
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/HelpdeskController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/HelpdeskController.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtilsV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/EcommerceControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/TransactionInfoUtils.kt
Labels: size/large, major, chart-major

#220 chore(kotlin): [CHK-4301] upgrade kotlin version
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
Labels: size/large, minor, chart-minor
