Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2025-02, with the labels that each got.

#181 chore: PIDM-130 increase page size for DL
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceController.kt
Labels: patch, chart-patch, size/small

#180 [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions
  .devops/code-review-pipelines.yml
Labels: skip-release, ignore-for-release, size/small

#182 fix: api tests for DLQ over limit
  api-tests/v1/eCommerce-helpdesk.api.tests.dev.json
  api-tests/v1/eCommerce-helpdesk.api.tests.local.json
  api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
Labels: patch, chart-patch, size/small

#184 chore: update github release task
  .devops/azure-templates/gradle-github-release.yml
Labels: patch, chart-patch, size/small

#185 fix: [PIDM-133] add filters search deadletter events
  api-spec/v1/openapi.yaml
  api-tests/v1/eCommerce-helpdesk.api.tests.dev.json
  api-tests/v1/eCommerce-helpdesk.api.tests.local.json
  api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
  docker/mongoDB/mongo-init.js
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/repositories/ecommerce/DeadLetterRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/mongo/DeadLetterDataProvider.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v1/DeadLetterDataProviderTest.kt
Labels: size/large, minor, chart-minor

#186 fix: [PIDM-133] time range in test
  api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
Labels: size/small, minor, chart-minor

#187 [PIDM-214] chore(ecommerce): enable search pm in ecommerce history
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, chart-patch, size/small

#188 [PIDM-256] Enable search pm in ecommerce history
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, chart-patch, size/small

#189 fix: default value management for transaction fields
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/documents/PmTransactionHistory.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/ResponseBuilderV1.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/PmTransactionHistoryDataProviderTestV2.kt
Labels: bug, patch, chart-patch, size/small
