Repository pagopa/pagopa-ecommerce-helpdesk-service, pull requests merged in 2025-04, with the labels that each got.

#197 [CHK-4050] Added search by fiscal code
  api-spec/v2/openapi.yaml
  build.gradle.kts
  gradle.lockfile
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/repositories/ecommerce/TransactionsViewRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/mongo/EcommerceTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/EcommerceTransactionDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialDataCacheUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialFiscalCodeUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialMailUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/SearchParamDecoderV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/EcommerceForTransactionV1DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/EcommerceForTransactionV2DataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/PmTransactionHistoryDataProviderTestV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/v2/PMTransactionDataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialFiscalCodeUtilsTests.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialMailUtilsTests.kt
Labels: size/small, minor, chart-minor

#199 [CHK-4050] FiscalCode and Email use different keys for encryption
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/configurations/WebClientsConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialDataCacheUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/configurations/WebClientsConfigTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/HelpdeskServiceTest.kt
  src/test/resources/application.properties
Labels: size/small, minor, chart-minor

#200 feat: npg google pay api key management
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/configurations/NpgPspsApiKeyConfigBuilder.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/EcommerceTransactionDataProvider.kt
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: size/small, minor, chart-minor

#202 feat: CHK-4077 Add new api metrics with mock response
  api-spec/v2/openapi.yaml
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/EcommerceController.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceService.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtilsV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v2/EcommerceControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceServiceTest.kt
Labels: skip-release, ignore-for-release, size/small

#205 [PIDM-454] fix: expanded prod rollback trigger conditions
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#203 Chk 4078 add dataprovider metrics
  .env.example
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/MetricsProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/repositories/ecommerce/TransactionsViewRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/StateMetricsDataProvider.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/documents/EcommerceStatusCount.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceService.kt
  src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/v2/ResponseBuilderV2.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/v2/StateMetricsDataProviderTest.kt
  src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v2/EcommerceServiceTest.kt
Labels: patch, chart-patch, size/small

#207 fix: deploy pipeline version bump
  .devops/azure-templates/gradle-github-release.yml
  .devops/deploy-pipelines.yml
  .github/workflows/deploy.yml
  .github/workflows/semver_release.yaml
Labels: size/large, patch, chart-patch
